services:
  postgres:
    image: postgres:16-alpine
    container_name: hoard_keeper_db
    environment:
      POSTGRES_DB: hoard_keeper_db
      POSTGRES_USER: hoard_user
      POSTGRES_PASSWORD: hoard_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: